before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - chmod +x gradlew

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

env:
  matrix:
    - GRADLE_OPTS="-Xms1g -Xmx3g"

git:
  depth: 3

install: true

jdk:
  - oraclejdk8

language: java
script: "./gradlew build --refresh-dependencies"
